name: Mirror to Personal Repo

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Mirror repository to Personal Repo for the timebeing
        run: |
          REPO_URL="https://github.com/TheDaniel3131/cosmo-converter.git"
          git remote add mirror "$REPO_URL"
          git push --force mirror main:main
