name: Mirror to Personal Repo

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Clean repository
        run: |
          git add .
          git commit -m "Commit all changes before filtering" || true
          git branch -D main || true
          git checkout --orphan main

      - name: Mirror repository
        run: |
          REPO_URL="git@github.com:TheDaniel3131/cosmo-converter.git"
          git clone --bare $REPO_URL temp-repo
          cd temp-repo
          git filter-repo --to-refs main --path .github/workflows --invert-paths
          git remote add origin $REPO_URL
          git push origin --all --force
          git push origin --tags --force
