name: Mirror to Personal Repo

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Create archive
        run: git archive --format tar.gz --output archive.tar.gz HEAD:./ .github/workflows

      - name: Push to personal repo
        run: |
          git remote add mirror "https://TheDaniel3131:${{ secrets.PERSONAL_REPO_TOKEN }}@github.com/TheDaniel3131/cosmo-converter.git"
          git push --force mirror main:main
