name: Mirror to Personal Repo

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Ensure .gitignore exists and contains .github/workflows
        run: |
          git remote add mirror git@github.com:TheDaniel3131/cosmo-converter.git
          git fetch mirror
          git checkout mirror/main
          if [ ! -f ".gitignore" ]; then
            echo ".gitignore file does not exist, creating one"
            touch .gitignore
          fi
          if ! grep -q ".github/workflows" .gitignore; then
            echo ".github/workflows >> .gitignore"
            echo ".github/workflows" >> .gitignore
            git add .gitignore
            git commit -m "Add .github/workflows to .gitignore"
            git push origin main
          fi

      - name: Remove .github/workflows (if exists)
        run: |
          git remote add mirror git@github.com:TheDaniel3131/cosmo-converter.git
          git fetch mirror
          git checkout mirror/main
          if [ -d ".github/workflows" ]; then
            git rm -rf .github/workflows
            git commit -m "Remove .github/workflows directory"
            git push origin main
          else
            echo ".github/workflows directory does not exist, skipping removal"
          fi
