name: Mirror to Personal Repo

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Mirror repository
        run: |
          git remote add mirror git@github.com:TheDaniel3131/cosmo-converter.git
          git push --force mirror main:main
